### ISSUE TITLE
test suite not generated.

### ISSUE THREAD

**Issue by targetnull** [libbitcoin/libbitcoin-network#141]
Hi, I download the latest source code and successfully compiled using `make && make install`. However, there is no binary file generated in the `test` directory, is it expected or I missed something? Thanks.

**Comment by pmienk** [comment]
As per automake, `make` builds libraries and programs defined in Makefile.am.  Tests are neither and build only when running `make check` - note that this also executes the tests.  This is a conscious choice, as the test executables could be defined as `noinst_`, however those cases in which tests will not be executed then suffer from forced test compilation.
