### ISSUE TITLE
Need one more fork to make Homebrew formula

### ISSUE THREAD

**Issue by sugarjig** [libbitcoin/libbitcoin-network#188]
Hi all! I've made Homebrew formulae out of most of the libbitcoin repos, but there are still a few more to go, including this one. To get dependent repos to build (e.g. libbitcoin-node), I have to define libbitcoin-network as a "resource", which makes the build process a little bit more complicated. If I can define other Homebrew formulae as dependencies, it's easier.

In order to make a formula, Homebrew requires a repo to be "canonical," which means it needs either 20 watchers, 25 stars, or 20 forks. libbitcoin-network needs just one more fork! If any followers of this repo haven't forked it (or starred it), I would greatly appreciate it if you did! Or if you already have, please pass on the word!

Thanks in advance!

**Comment by evoskuil** [comment]
Maybe repost to the libbitcoin mailling list.

**Comment by sugarjig** [comment]
Will do! In the meantime, we got one more fork of this repo, so I'm off to make a Homebrew formula!

**Comment by evoskuil** [comment]
We need to get these into code generation.

**Comment by sugarjig** [comment]
Is there something I can do to help with that?

**Comment by sugarjig** [comment]
Related question: were the 3.4.0 releases of all the repos re-done? I've been having problems with mismatching shasums recently. Looking back, I upgraded the Homebrew formula to 3.4.0 on Dec. 17, but the release dates say Dec. 25.

**Comment by evoskuil** [comment]
Yes, sorry.

**Comment by sugarjig** [comment]
Ah, okay. That presents a bit of a problem for Homebrew. Their build system will refuse updates that merely change the shasum of a file. They consider it potentially malicious. Any chance we can make a v3.4.1 tag (or whatever version scheme you prefer)?

**Comment by evoskuil** [comment]
I’m about to tag 3.5.0.

**Comment by sugarjig** [comment]
Even better!

**Comment by evoskuil** [comment]
All done.

**Comment by sugarjig** [comment]
Great! Thank you!
