### ISSUE TITLE
install script compilation error: ambiguous call to network::proxy::stop()

### ISSUE THREAD

**Issue by VonBotteicher** [libbitcoin/libbitcoin-network#267]
I'm attempting to build the latest version3 (commit #336d7c59be5a543a3ce7291ad1743f25032eeede)  using the install script, invoked like so `PARALLEL=12 ./install.sh --prefix=/home/$(whoami)/libbitcoin --build-boost --build-zmq` 

I get the following error:

![image](https://user-images.githubusercontent.com/66533025/204009452-84d10b05-afa3-4137-9a3e-e69ee565a12c.png)

Since the libbitcoin-network README does not mention the install script I tried the following

```
$ ./autogen.sh
$ ./configure
$ make
```

... and got the same error.  Any ideas what my problem is?

On a more general note - is there a slack or a discord that would be more appropriate to post questions like this that are likely mistakes I'm making and not actual problems with the library? Thanks

**Comment by evoskuil** [comment]
The libbitcoin slack is [here](https://libbitcoin.slack.com).

**Comment by pmienk** [comment]
@VonBotteicher please provide full output from `install.sh` executed against a clean prefix either here or in [slack](https://libbitcoin.slack.com).

**Comment by VonBotteicher** [comment]
@pmienk blowing away the the prefix directory did the trick, I suspect I had previous installs with a different boost version... not sure why the new install didn't supercede the previous if that were the case... anyhoo thanks so much for the help! I'm now able to build the explorer and the server and all dependent submodules.
