### ISSUE TITLE
subscribe

### ISSUE THREAD

**Issue by virus-cyber** [libbitcoin/libbitcoin-network#435]
hi what am i doing wrong why doesnt it want to work
```
			channel->subscribe<bc::message::transaction>(
				block_subscription_handler);

			// Send get_data(inv(type, hash)).
			const auto type = bc::message::inventory_vector::type_id::transaction;
			hash_digest hash;
			bc::message::inventory_vector inv_vector(type, hash);
			bc::message::get_data get_data_msg({ inv_vector });
			
			channel->send(get_data_msg, send_handler);
```

I wanted to receive new transactions

**Comment by virus-cyber** [comment]
can't anyone help?

**Comment by evoskuil** [comment]
It looks like you are requesting a tx with a null hash (default hash value). There is no such tx, so should not expect a response.

**Comment by virus-cyber** [comment]
thanks for the answer, but how do I do it correctly?

**Comment by evoskuil** [comment]
That’s not a simple answer.

**Comment by virus-cyber** [comment]
I just wanted to stay updated on new transactions

**Comment by virus-cyber** [comment]
libbitcoin-network
it is not able to subscribe to the channel tx?

**Comment by evoskuil** [comment]
libbitcoin-network is a library, not an application. The library does not include a tx or block protocol, because there is no associated store, that requires libbitcoin-node, which derives from network. That in turn requires an application to expose the subscription, such as libbitcoin-server, which derives from node.

**Comment by evoskuil** [comment]
libbitcoin-explorer provides a client command that can subscribe to tx notifications from libbitcoin-server (mentioned previously).

**Comment by virus-cyber** [comment]
it turns out that to subscribe to new transactions you need to install all your offers + 600 g of blockchain

**Comment by evoskuil** [comment]
Lolz. No, you need an application (process). I gave you an example. You can certainly write something using network to capture tx announcements and request announced txs and store them somewhere, etc.

**Comment by evoskuil** [comment]
I pointed out earlier that you were requesting the tx with a null hash. You need to subscribe to inv messages and filter out tx announcements and then request the txs for relay that you want, and subscribe to tx messages to get those.

**Comment by virus-cyber** [comment]
This is exactly what I want but I can't figure out how to do it. Can you help me do it?

**Comment by evoskuil** [comment]
I don’t have the bandwidth to write you an application, but myself and others can help with questions. You could join the slack channel. This isn’t the place for that type of thing. Open link on the system wiki menu.

**Comment by virus-cyber** [comment]
but telegram won't work for this

**Comment by evoskuil** [comment]
Moved to Slack
